export default {
  "create-adjustment": [
    { info: "Solid Color", value: "solidColorLayer" },
    { info: "Gradient", value: "gradientLayer" },
    { info: "Pattern", value: "patternLayer" },
    { info: "Brightness", value: "brightnessEvent" },
    { info: "Levels", value: "levels" },
    { info: "Curves", value: "curves" },
    { info: "Exposure", value: "exposure" },
    { info: "Vibrance", value: "vibrance" },
    { info: "Hue/Saturation", value: "hueSaturation" },
    { info: "Color Balance", value: "colorBalance" },
    { info: "Black and White", value: "blackAndWhite" },
    { info: "Photo Filter", value: "photoFilter" },
    { info: "Channel Mixer", value: "channelMixer" },
    { info: "Color Lookup", value: "colorLookup" },
    { info: "Invert", value: "invert" },
    { info: "Posterize", value: "posterization" },
    { info: "Threshold", value: "thresholdClassEvent" },
    { info: "Gradient Map", value: "gradientMapClass" },
    { info: "Selective Color", value: "selectiveColor" },
  ],
  "quick-action": [
    { info: "Switch primary/secondary color", value: "switch-colors" },
    { info: "Merge visible layers on top", value: "merge-visible-duplicate" },
    { info: "Create layer mask", value: "create-layer-mask" },
    { info: "Content-aware auto fill", value: "content-fill" },
    { info: "Switch last/current tool", value: "toggle-tool" },
  ],
};
