export default {
  "tool-parameter": [
    { info: "Angle", value: "angle" },
    { info: "Flow", value: "flow" },
    { info: "Hardness", value: "hardness" },
    //{info: "Mode", value : "mode"},
    { info: "Opacity", value: "opacity" },
    { info: "Pressure", value: "pressure" },
    { info: "Roundness", value: "roundness" },
    { info: "Size", value: "size" },
    { info: "Smoothing", value: "smoothing" },
    { info: "Spacing", value: "spacing" },
  ],
  "image-adjustment": [
    { info: "Brightness", value: "brigthness" },
    { info: "Contrast", value: "contrast" },
    { info: "Hue", value: "hue" },
    { info: "Lightness", value: "lightness" },
    { info: "Saturation", value: "saturation" },
  ],
  "adjust-adjustment": [
    { info: "Brightness", value: "brightness" },
    { info: "Contrast", value: "contrast" },
    { info: "Exposure", value: "exposure" },
    { info: "Offset", value: "offset" },
    { info: "Gamma", value: "gamma" },
    { info: "Vibrance", value: "vibrance" },
    { info: "Vibrance Saturation", value: "vibranceSaturation" },
    { info: "Hue", value: "hue" },
    { info: "Saturation", value: "saturation" },
    { info: "Lightness", value: "lightness" },
  ],
  "custom-keys": [
    { info: "Overlay Control Key", value: "overlay-control" },
    { info: "Spacebar Shortcut", value: "spacebar-shortcut" },
  ],
};
